/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type UserRole = "admin" | "user";

export interface GameSeasons {
  createdAt: Generated<Timestamp>;
  endsAt: Timestamp;
  id: string;
  name: string;
  seasonNumber: number;
  startsAt: Timestamp;
  status: Generated<string>;
  worldId: string;
}

export interface GameWorlds {
  createdAt: Generated<Timestamp>;
  description: Generated<string>;
  id: string;
  name: string;
  region: Generated<string>;
  slug: string;
  status: Generated<string>;
}

export interface Kingdoms {
  createdAt: Generated<Timestamp>;
  food: Generated<Int8>;
  gold: Generated<Int8>;
  id: string;
  lastEconomyAt: Generated<Timestamp>;
  name: string;
  ownerUserId: number;
  stone: Generated<Int8>;
  wood: Generated<Int8>;
  worldId: string;
}

export interface LoginAttempts {
  attemptedAt: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  success: Generated<boolean | null>;
}

export interface PlayerProfiles {
  createdAt: Generated<Timestamp>;
  displayName: string;
  id: Generated<Int8>;
  lastActiveAt: Generated<Timestamp>;
  userId: number;
  worldId: string;
}

export interface SeasonResults {
  id: Generated<Int8>;
  points: Generated<Int8>;
  rank: number | null;
  rewardClaimed: Generated<boolean>;
  seasonId: string;
  snapshot: Generated<Json>;
  updatedAt: Generated<Timestamp>;
  userId: number;
}

export interface Sessions {
  createdAt: Generated<Timestamp | null>;
  expiresAt: Timestamp;
  id: string;
  lastAccessed: Generated<Timestamp | null>;
  userId: number;
}

export interface UserPasswords {
  createdAt: Generated<Timestamp | null>;
  id: Generated<number>;
  passwordHash: string;
  userId: number;
}

export interface Users {
  avatarUrl: string | null;
  createdAt: Generated<Timestamp | null>;
  displayName: string;
  email: string;
  id: Generated<number>;
  role: Generated<UserRole>;
  updatedAt: Generated<Timestamp | null>;
}

export interface WorldEvents {
  actorUserId: number | null;
  createdAt: Generated<Timestamp>;
  eventType: string;
  id: Generated<Int8>;
  payload: Generated<Json>;
  worldId: string;
}

export interface WorldMemberships {
  id: Generated<Int8>;
  joinedAt: Generated<Timestamp>;
  userId: number;
  worldId: string;
}

export interface DB {
  gameSeasons: GameSeasons;
  gameWorlds: GameWorlds;
  kingdoms: Kingdoms;
  loginAttempts: LoginAttempts;
  playerProfiles: PlayerProfiles;
  seasonResults: SeasonResults;
  sessions: Sessions;
  userPasswords: UserPasswords;
  users: Users;
  worldEvents: WorldEvents;
  worldMemberships: WorldMemberships;
}


// Use these for zod schema enums or other purposes, since the kysely enums are just types
export const UserRoleArrayValues: [UserRole, ...UserRole[]] = ["admin","user"];
// Table/column names whose snake_case spelling kysely's default CamelCasePlugin
// cannot recover from the camelCase name used in code (an underscore directly
// before a digit, e.g. reminder_48h_sent ⇄ reminder48hSent). The db helper's
// CamelCasePlugin subclass consults this map so those identifiers work in
// queries. Regenerated on every schema pull.
export const kyselyIdentifierOverrides: Record<string, string> = {};

// Note: kysely maps the table/column/enum names from snake_case to camelCase and PascalCase. When running SQL statements, make sure to use snake_case, but TypeScript code should use camelCase or PascalCase.
